### ISSUE TITLE
when using rtl language tab underline in wrong position 

### ISSUE THREAD

**Issue by elirangoshen** [react-navigation/tabs#118]
### Current behaviour

In rtl layout the tabs underline located in wrong position.
I'm using createMaterialTopBarNavigator

### Expected behaviour

When using rtl language, the tab underline should be under the tab header/name 

### Code sample
```
export const TabStack = createMaterialTopTabNavigator({
  moneyTransfer: { screen: MoneyTransferScreen },
  withdrawal: { screen: WithdrawalScreen },
  pendingRequests: { screen: PendingRequestsScreen },

},
  {
    defaultNavigationOptions: {
      drawerLabel: translate("operations.label"),
    },
    lazy: true,
    tabBarOptions: {
      activeBackgroundColor: color.palette.lightGrey,
      inactiveBackgroundColor: color.palette.lightGrey,
      scrollEnabled: true,
      style: {
        backgroundColor: "#212121",
      },
      indicatorStyle: {
        backgroundColor: color.palette.green,
      },
      labelStyle: {
        width: 200,
      },

    },
    animationEnabled: true,
  })
```

### Screenshots (if applicable)

<img width="374" alt="Screen Shot 2019-04-16 at 5 07 01 PM" src="https://user-images.githubusercontent.com/9560116/56222227-f209b380-606b-11e9-878c-6cb64aab4de7.png">

### What have you tried

didn't tried anything yet as id like to know if there is solution without me need to supply workaround from code 

### Your Environment

| software              | version
| --------------------- | -------
| ios       |  12.2
| react-native          | 0.59.2
| react-navigation-tabs | 2.1.0
| node                  |  11.14.0
| yarn           |  1.15.2

**Comment by elirangoshen** [comment]
@satya164 , this can be workaround by disabling swipe gestures and animations.
But its still not solution so id prefer to leave it open
I does want to reference more serious manner that I opened : 
https://github.com/react-native-community/react-native-tab-view/issues/746
For this I cannot find any workaround, tabs just not rendered.
It looks like there's some fix in new version of tab-view related to rtl pager, but I'm using react-navigaion-tabs and in the latest version its still uses older version to tab-view. is it possible you would upgrade tab-view version ?

**Comment by satya164** [comment]
There's a PR open for it, but it doesn't seem to work for me. Help is appreciated https://github.com/react-native-community/react-native-tab-view/pull/742

**Comment by satya164** [comment]
This should fix it https://github.com/react-native-community/react-native-tab-view/pull/808
