### ISSUE TITLE
tabBarVisible not working 

### ISSUE THREAD

**Issue by CosmicSage** [react-navigation/tabs#122]
### Current behaviour

tabBarVisible is not hiding the TabBar at the bottom

### Expected behaviour

TabBar should be hidden

### Code sample
  /** navigation.state.index is undefined
      Therefore used routeName
  **/
  static navigationOptions = ({ navigation }) => {
  navigationOptions = {
    title: navigation.getParam('Title', 'Info Unavialable'),
  };
  if (navigation.state.routeName === "Details") {
    navigationOptions.tabBarVisible = false;
  }
  return navigationOptions;
};
The Snack : https://snack.expo.io/@coldlinux/trembling-candies
The issue most probably lies in the DetailsScreen.js file inside screens directory

### What have you tried

I've read issue #19 and #20 and also read 
https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-tab-navigator-contains-a-stack-and-you-want-to-hide-the-tab-bar-on-specific-screens
Tried the solutions mentioned in all of them

The code snippet is taken from DetailsScreen.js file and the entire projects is present on My profile under the name "Project2"
### Your Environment

| software              | version
| --------------------- | -------
| react-native          |0.59
| react-navigation-tabs |3.0.9
| node                  |11.7.0
| npm or yarn           |6.9.0

**Comment by brentvatne** [comment]
hi! please provide a minimal reproducible example. more info on how to do this in https://stackoverflow.com/help/mcve

**Comment by CosmicSage** [comment]
Hi brent I've added a Snack which very close to the real Project. CheckOut the DetailsScreen.js file

**Comment by eriveltonelias** [comment]
hi @CosmicSage,

you should use tabBarVisible on `StackNavigator.navigationOptions` instead of `DetailsScreen`

I just updated your snack https://snack.expo.io/@eriveltonelias/trembling-candies

**Comment by CosmicSage** [comment]
Thanks @eriveltonelias 

Replying late cause had a stupid exam 

Could I've had avoided this mistake?
