### ISSUE TITLE
Knowing wether or not the user is swiping the material top bar navigator

### ISSUE THREAD

**Issue by jordy-wijman** [react-navigation/tabs#127]
### Current behaviour

I'm trying to hook onto the isSwiping property of the material top bar navigator, so I can transition my shared component (that is shared over all the tabs) whenever the animation is starting and ending. Currently there is no way to do this.

### Expected behaviour

It would be awesome if a prop would be sent back that would indicate wether the animation is happening yes or no. I know that you can hook onto react navigations' didBlur and willFocus events, but these happen too late. They happen whenever the transition is done.

### Code sample

      <View style={styles.container}>
        <FavoritesNavigator navigation={navigation} />
        /** I want to transition this floating action button when the navigator changes OR starts
        swiping, however we currently can't hook onto 'isAnimating' or anything like that. */
        <FAB
          icon="add"
          color="white"
          style={styles.fab}
          onPress={() =>
            navigation.navigate(
              navigation.state.index === 0
                ? NavigationScreens.TRIP_DETAIL_SCREEN
                : NavigationScreens.LABEL_DETAIL_SCREEN,
            )
          }
        />
      </View>

### What have you tried
Looked at the implementation of the createMaterialTopBarNavigator and couldn't find an API available here that I could use.

**Comment by IshuSinghalTT** [comment]
Facing the same issue, I have to handle keyboard on the basis of swiping events but there is no API available for same. Did you find anything ?

**Comment by jordy-wijman** [comment]
Unfortunately not, I had to accept the fact that it wasn't there @IshuSinghalTT

**Comment by haialaluf** [comment]
Facing the same issue, in react navigation 3 I used the panX and offsetX (they where on header props) they are not available anymore on react navigation 4, I saw the position object on header props instead witch is react-native-reanimated Node, I have tried to use it, but it not seams to work.

Anyone here who know what this about? I saw in the source code of react-native-community/react-native-tab-view they do use this position prop, but for me swiping doesn't really affect the position.

**Comment by lake2** [comment]
Same issue +1

**Comment by lake2** [comment]
Finally I find solution by myself, just use the low-level implemention of material top navigator : https://github.com/react-native-community/react-native-tab-view as the documention say:

> React Navigation integration can be achieved by the react-navigation-tabs package. Note that while it's easier to use, it is not as flexible as using the library directly.

It provides `onSwipeStart`, `onSwipeEnd`, `gestureHandlerProps`, and the most important, the  current index of the tab is a state, which you can use to implements your own animations.

See the underline animation when change the Tab, which I implements by `react-native-tab-view`:

![screencast-genymotion-2019-10-15_19 59 53 122 00_00_02--00_00_08](https://user-images.githubusercontent.com/6293752/66830423-04679a00-ef88-11e9-84f7-d6e62e13766e.gif)

**Comment by satya164** [comment]
We want to dispatch `swipeStart` and `swipeEnd` events if similar to [how we're dispatching `refocus` event](https://github.com/react-navigation/tabs/blob/f27327cec5089b72796b393f55227e6719e029a1/src/utils/createTabNavigator.tsx#L151) if someone wants to work on it.
