### ISSUE TITLE
TypeError: Cannot read property 'out' of undefined

### ISSUE THREAD

**Issue by nwaughachukwuma** [react-navigation/tabs#128]
Hey guys, am having following error message:  `TypeError: Cannot read property 'out' of undefined` when using and testing components that use react-navigation-tabs. Basically, how can I mock this module?

@brentvatne @satya164

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.59.8
| react-navigation-tabs | 2.1.2
| node                  | 8.11.3
| npm or yarn           | yarn (1.15.2)

**Comment by satya164** [comment]
Check this out: https://github.com/kmagiera/react-native-reanimated/pull/276

**Comment by nwaughachukwuma** [comment]
Hi @satya164 thanks for the quick response. I don't think I get the point in that react-native-reanimated issue. But please be aware that I have mocked react-native-reanimated using the code below:

```
jest.mock('react-native-reanimated', () => {

  const {View} = require('react-native');
  return {
    Value: jest.fn(),
    event: jest.fn(),
    add: jest.fn(),
    eq: jest.fn(),
    set: jest.fn(),
    cond: jest.fn(),
    interpolate: jest.fn(),
    View,
    Extrapolate: { CLAMP: jest.fn() },
    Transition: {
      Together: 'Together',
      Out: 'Out',
      In: 'In',
    }
  };
});
```

What else should I know and do?

**Comment by satya164** [comment]
It's not possible to know where the error is coming from without the full stacktrace.

**Comment by nwaughachukwuma** [comment]
Ooh that. I will update the main post ASAP.

**Comment by satya164** [comment]
Also I'll recommend to copy the mock from the PR I linked which is a full mock rather than writing your own.

**Comment by nwaughachukwuma** [comment]
Alright @satya164. The test now passes after I added options for Easing in the returned object. The final mock code now looks like below:

```
jest.mock('react-native-reanimated', () => {

  const {View} = require('react-native');
  return {
    Value: jest.fn(),
    event: jest.fn(),
    add: jest.fn(),
    eq: jest.fn(),
    set: jest.fn(),
    cond: jest.fn(),
    interpolate: jest.fn(),
    View,
    Extrapolate: { CLAMP: jest.fn() },
    Transition: {
      Together: 'Together',
      Out: 'Out',
      In: 'In',
    },
    Easing: { <=== added this
      in: jest.fn(),
      out: jest.fn(),
      inOut: jest.fn(),
    },
  };
});
``` 
Now it works
