### ISSUE TITLE
Delay switching between tabs

### ISSUE THREAD

**Issue by brunohkbx** [react-navigation/tabs#130]
Hello everyone.
I followed this example from docs to dynamically set `headerTitle` according to the current tab.
https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-stack-contains-a-tab-navigator-and-you-want-to-set-the-title-on-the-stack-header

It works. However, there's a delay to set `headerTitle` when the tab is swiped.
Related to: #578, #1230

![bug](https://user-images.githubusercontent.com/6487206/57237679-179c3400-6ffe-11e9-9076-906cc20f5c82.gif)

### Your Environment
| software         | version
| ---------------- | -------
| react-navigation | ^3.9.1
| react-native     | https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz
| node             | v10.15.3
| npm or yarn      | yarn@1.13.0-20181121.1436

### How to reproduce
https://snack.expo.io/@bruno.castro/react-navigation-tabs

**Comment by brunohkbx** [comment]
@satya164 I've updated react-navigation in my application to `^3.11.0` and I'm still experiencing this problem.
Did I miss something? :thinking:

**Comment by satya164** [comment]
You need to use the `react-navigation-tabs` package

**Comment by brunohkbx** [comment]
@satya164  I've tried importing from `react-navigation-tabs` using the versions: `1.1.4` and `2.1.2`.
I've still got the same results from this picture :cry: 

> Hello everyone.
> I followed this example from docs to dynamically set `headerTitle` according to the current tab.
> https://reactnavigation.org/docs/en/navigation-options-resolution.html#a-stack-contains-a-tab-navigator-and-you-want-to-set-the-title-on-the-stack-header
> 
> It works. However, there's a delay to set `headerTitle` when the tab is swiped.
> Related to: #578, #1230
> 
> ![bug](https://user-images.githubusercontent.com/6487206/57237679-179c3400-6ffe-11e9-9076-906cc20f5c82.gif)
> 
> ### Your Environment
> software	version
> react-navigation	^3.9.1
> react-native	https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz
> node	v10.15.3
> npm or yarn	yarn@1.13.0-20181121.1436
> ### How to reproduce
> https://snack.expo.io/@bruno.castro/react-navigation-tabs

**Comment by satya164** [comment]
Ha. I forgot to publish the new version. Please try now.

**Comment by brunohkbx** [comment]
Awesome @satya164. It looks much more smooth now.
![tabs](https://user-images.githubusercontent.com/6487206/58040812-ccf5de00-7b0c-11e9-9e08-b8ca3560a16d.gif)
