### ISSUE TITLE
createMaterialTopTabNavigator backgroundColor not defaulting to theme primary color

### ISSUE THREAD

**Issue by jorrharris** [react-navigation/tabs#140]
I am trying to use my theme primary color for the background of my createMaterialTopTabNavigator, but it is not defaulting to the theme color, and I can't access the theme outside of a component.

Basically I am using React-Native-Paper's default theme right now and it looks something like this (This purple color is the color I want):

[![enter image description here][1]][1]

Now the MaterialTopBarNavigator looks like this (It's not using the theme's default purple color):
[![enter image description here][2]][2]

So basically, I am trying to find a way to access my theme outside of a component so I can pass it into the style object in createMaterialTopTabNavigator tabBarOptions

My index.js looks like this
```
const myDarkTheme = {
  ...DarkTheme,
  headerDark: true
};

const myDefaultTheme = {
  ...DefaultTheme,
  headerDark: true
};

export const ThemeContext = React.createContext(null);

export default class Main extends Component {
  state = {
    theme: myDefaultTheme
  };

  _toggleTheme = () => {
    this.setState(prevState => {
      return {
        theme: prevState.theme.dark ? myDefaultTheme : myDarkTheme
      };
    });
  };

  render() {
    return (
      <ThemeContext.Provider
        value={{ theme: this.state.theme, toggleTheme: this._toggleTheme }}
      >
        <PaperProvider theme={this.state.theme}>
          <App />
        </PaperProvider>
      </ThemeContext.Provider>
    );
  }
}

AppRegistry.registerComponent(appName, () => Main);
```

Here is my createMaterialTopTabNavigator
```
const AccountNavigator = createMaterialTopTabNavigator(
  {
    Profile: { screen: Profile },
    Preferences: { screen: Preferences }
  },
  {
    initialRouteName: "Profile",
    swipeEnabled: true,
    animationEnabled: true,
    tabBarOptions: {
      labelStyle: { fontWeight: "bold" },
      //I would add this here to change background color
      //but I don't know how to access my theme color from here...
      //style: { backgroundColor: insertThemePrimaryColorHere }
    }
  }
);
```

  [1]: https://i.stack.imgur.com/k7dir.png
  [2]: https://i.stack.imgur.com/ZKAx9.png

**Comment by Notcracker** [comment]
Go the same issue, any solution?

**Comment by satya164** [comment]
`createMaterialTopTabNavigator` uses `react-native-tab-view`, your theme is from `react-native-paper`. There's no way it'll know about your theme (you could also be using a different library for theme). You need to wrap the exported `MaterialTopTabBar` to use background color from your theme. You can't pass it in `tabBarOptions`.

```js
tabBarComponent: withTheme(theme =>
  <MaterialTopTabBar style={{ backgroundColor: theme.colors.primary }} />
)
```

**Comment by zackify** [comment]
Where is withTheme imported from? I cant find it. Trying to get theming to work with the material top bar as well

**Comment by zackify** [comment]
Thanks for this, i was able to get mine to work this way

```
 tabBarComponent: ({ ...rest }) => {
              let { theme } = useAppContext(); 
              return (
                <MaterialTopTabBar
                  style={{ backgroundColor: theme.backgroundColor }}
                  labelStyle={{
                    color: theme.color,
                  }}
                  {...rest}
                />
              );
            },
```

I didn't see this mentioned on the themes page though, might want to mention that the material ones dont use the theme prop?

**Comment by satya164** [comment]
@zackify this seems to be different issue (the original issue is about react native paper theme). can you open a new issue about it? probably an oversight

**Comment by zackify** [comment]
You sure? I was noticing that the dark theme prop doesn't update the material tab theme (seems similar to this) and that i also couldn't specify `light` and `dark` keys for colors in the options. I can make a new ticket if you want.

**Comment by satya164** [comment]
@zackify read the first issue, it's talking about react-native-paper theme, not the light/dark theme in react navigation.
