### ISSUE TITLE
How to hide createMaterialTopNavigator

### ISSUE THREAD

**Issue by bachlongkocanh** [react-navigation/tabs#148]
I want hide createMaterialTopNavigator but not found props `TabBarVisible`. Can any one help me?? 
I want use createMaterialTopNavigator because it have `swipeEnabled` and animation `swipe`.

**Comment by satya164** [comment]
```js
tabBarComponent: () => null
```

**Comment by bachlongkocanh** [comment]
But I just want it hidden on some screens, is there any other ways to config it in tabbarOptions?

**Comment by satya164** [comment]
It's not possible
