### ISSUE TITLE
keyboardHidesTabBar should instantly hide tab bar

### ISSUE THREAD

**Issue by Robinfr** [react-navigation/tabs#149]
### Current behaviour
Currently it animates down

### Expected behaviour
I would like it to instantly disappear to improve the experience.

**Comment by osdnk** [comment]
Maybe it can depend on some param?

**Comment by satya164** [comment]
Without the animation it'll be sudden after the keyboard is shown (on Android anyways), which will make it look like there's a blink, not a better experience imo.

**Comment by Robinfr** [comment]
Based on some params or options would also be fine.
