### ISSUE TITLE
Delay on tab press

### ISSUE THREAD

**Issue by Rebsos** [react-navigation/tabs#150]
There were a lot of issues about a delay when pressing a tab in react-native-tab-view. But there may be a second problem, if you use it through react-navigation-tabs:

### Current behaviour

Delayed transition on tab press when importing createMaterialTopTabNavigator from react-navigation-tabs (latest 2.2.0)

**Touch -> Ripple -> Transition**

### Expected behaviour

Not delayed transition on importing createMaterialTopTabNavigator from react-navigation (latest 3.11.1) or pure react-native-tab-view (latest 2.9.0)

**Touch -> Transition -> Ripple**

### Code sample

git@github.com:Rebsos/react-navigation-tabs-delay-demo.git

### Screenshots (if applicable)

![](https://raw.githubusercontent.com/Rebsos/react-navigation-tabs-delay-demo/master/react-navigation-tabs-delay-demo.gif)

### What have you tried

Pure react-native-tab-view (latest) does not have this problem. Pure React-Navigation (without import createMaterialTopTabNavigator from react-navigation-tabs) does also not have this problem, it uses an older version of react-navigation-tabs. Occurs in release and dev mode.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.59.10
| react-navigation-tabs | 2.2.0
| node                  | 8.12.0
| npm or yarn           | yarn

**Comment by paolospag** [comment]
+1
@satya164

**Comment by fbartho** [comment]
React-navigation/tabs just updated to the latest tab-view, this morning.

**Comment by Rebsos** [comment]
The last update did not fix the problem (tested). I've updated the repository demo with the latest version of react-navigation-tabs (2.3.0).

**Comment by axelraymundo** [comment]
I tried using react-native-tab-view with a custom renderScene to pass the navigation prop and it behaves the same as the current behaviour which is delayed on tab press. 

I'm assuming react-navigation/tabs used a custom **renderScene** function for react-native-tab-view to pass the navigation props that's why it's slow/delayed.

**Comment by dubinam** [comment]
The same issue, android manage it too slow

**Comment by jiangbophd** [comment]
there is big issue, too slow when click to change tab. why ?

**Comment by jiangbophd** [comment]
what is time can fixed?

**Comment by satya164** [comment]
@jiangbophd it's an open source project. if you have an issue, send a pull request

**Comment by santiagoalmeidabolannos** [comment]
any better ideas?

**Comment by sirajalam049** [comment]
I'm going to leave this here.

https://facebook.github.io/react-native/docs/interactionmanager
