### ISSUE TITLE
Cannot read property 'light' of undefined

### ISSUE THREAD

**Issue by axelraymundo** [react-navigation/tabs#156]
### Current behaviour

Getting a "Cannot read property 'light' of undefined"

### Expected behaviour

Should have just replaced my react navigation tab

### Code sample

I just typed "import { createBottomTabNavigator } from "react-navigation-tabs";" to import it

### What have you tried

Tried pod install on ios

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-navigation-tabs |
| node                  |
| npm or yarn           |

**Comment by brentvatne** [comment]
make sure you're using the latest version of react-navigation

**Comment by brentvatne** [comment]
closing because incomplete report

**Comment by nishant-dani** [comment]
I am getting the same problem.   The error is Cannot read property 'light' of undefined.  I have enclosed an image of the stack trace in the simulator.   

The problem occurs on the ios simulator when running react-native run-ios.
 
"react-native": "0.60.5"
"react-navigation-tabs": "^2.5.2"
Using npm to install packages.
  
![image](https://user-images.githubusercontent.com/10539008/64993257-77e39200-d88a-11e9-8bbb-5daaed5028b7.png)

**Comment by satya164** [comment]
Can you open a new issue with a minimal runnable demo? Without a demo, we can't debug it.

**Comment by nishant-dani** [comment]
I did a little investigation and replaced 
import { createBottomTabNavigator } from 'react-navigation-tabs'

with the following lines;
12. import { ThemeColors, withNavigation, type NavigationScreenProp, type NavigationState } from 'react-navigation'
13. console.log(`ThemeColors is ${ThemeColors} light is ${ThemeColors.light}`)

I get the same error on line 13.  So ThemeColors is not defined from react-navigation.  

====

I also tracked the line number using the character position in the stacktrace in the file BottomTabBar.js.  
tabBarLight:{backgroundColor:_reactNavigation.ThemeColors.light.header,borderTopColor:_reactNavigation.ThemeColors.light.headerBorder}

Is that helpful?  I could diagnose it further for you.  But clearly ThemeColors is somehow not available from react-navigation.

**Comment by nishant-dani** [comment]
On my analysis it appeared that it was a problem with metro not handling imports from the navigation package properly I changed 
experimentalImportSupport: true,
in metro.config.js.
Since then I have not hit the problem.  I hope this might help others as well.

**Comment by hejun041** [comment]
same here

**Comment by dl-husky73** [comment]
I am having the same problem, added the experimentalImportSupport: true, to metro.config.js still having the same error, undefined ThemeColors.light.   Did the metro.config work for everyone?

**Comment by nishant-dani** [comment]
@dl-husky73 - after the change to metro.config.js I ran the clean scripts that I have in package.json.   I remember doing that to make sure it was a clean start.
react-native start --reset-cache
watchman watch-del-all && rm -rf $TMPDIR/react-native-packager-cache-* && rm -rf $TMPDIR/metro-bundler-cache-* && rm -rf node_modules/ && rm -rf /tmp/haste-map-react-native-package && npm cache clean --force && npm install
You might try cleaning as well.

**Comment by dl-husky73** [comment]
> @dl-husky73 - after the change to metro.config.js I ran the clean scripts that I have in package.json. I remember doing that to make sure it was a clean start.
> react-native start --reset-cache
> watchman watch-del-all && rm -rf $TMPDIR/react-native-packager-cache-* && rm -rf $TMPDIR/metro-bundler-cache-* && rm -rf node_modules/ && rm -rf /tmp/haste-map-react-native-package && npm cache clean --force && npm install
> You might try cleaning as well.

Thanks so much nishant-dani, that worked.  I am back to a clean build.    I appreciate the quick reply, very helpful!

**Comment by Adibacaj** [comment]
> On my analysis it appeared that it was a problem with metro not handling imports from the navigation package properly I changed
> experimentalImportSupport: true,
> in metro.config.js.
> Since then I have not hit the problem. I hope this might help others as well.

That worked for me too, Thanks man

**Comment by JuxhinB** [comment]
> @dl-husky73 - after the change to metro.config.js I ran the clean scripts that I have in package.json. I remember doing that to make sure it was a clean start.
> react-native start --reset-cache
> watchman watch-del-all && rm -rf $TMPDIR/react-native-packager-cache-* && rm -rf $TMPDIR/metro-bundler-cache-* && rm -rf node_modules/ && rm -rf /tmp/haste-map-react-native-package && npm cache clean --force && npm install
> You might try cleaning as well.

Tried but still nothing...

**Comment by MianJawadAhmad** [comment]
Just upgrade react-navigation to 
`"react-navigation": "4.0.0"` in package.json
`rm -rf node_modules`
`npm install`
`react-native run-ios`
