### ISSUE TITLE
No typescript definitions.

### ISSUE THREAD

**Issue by localnet** [react-navigation/tabs#158]
### Current behaviour

After upgrade to react-navigation@4.0.0 and install react-navigation-tabs@2.3.0 manually, I can't found typescript definitions:

> error TS7016: Could not find a declaration file for module 'react-navigation-tabs'.

### Expected behaviour

Get Typescript definitions for react-navigation-tabs@2.3.0

### Code sample

`import { createBottomTabNavigator } from "react-navigation-tabs";`

### What have you tried

Continue importing `createBottomTabNavigator` from  react-navigation@4.0.0

`import { createBottomTabNavigator } from "react-navigation";`

> error TS2305: Module '"react-navigation"' has no exported member 'createBottomTabNavigator'.

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android (no relevant)
| react-native          | 0.60.5 (no relevant)
| react-navigation-tabs | 2.3.0
| node                  | 10.16.3 (no relevant)
| npm or yarn           | npm (no relevant)

**Comment by joshbax** [comment]
As a temporary work-around, copy the declarations file from react-navigation to your project (may need the last update to @types/react-navigation) and change the first line to `declare module react-navigation-tabs`. 

As far as I can tell the types haven't changed yet.

**Comment by brentvatne** [comment]
you can track the wip branch here: https://github.com/react-navigation/tabs/tree/%40satya164/typescript

**Comment by ScreamZ** [comment]
True, can you ping me when released ? thanks :)

**Comment by nvuhung** [comment]
Any update for this?

**Comment by brentvatne** [comment]
this pr landed and will be published soon https://github.com/react-navigation/tabs/pull/161

**Comment by osdnk** [comment]
It's no longer valid issue

**Comment by leotm** [comment]
I got this again from following https://github.com/react-navigation/react-navigation/releases/tag/v4.0.0 which mentions to install `react-navigation-tabs@^1.2.0`  _This will install the versions compatible with your code if you were using react-navigation@3.x, so you wouldn't need any more changes beyond changing the imports._. Fixed by just updating to the latest version.
