### ISSUE TITLE
Typescript definition is wrong

### ISSUE THREAD

**Issue by EternalChildren** [react-navigation/tabs#163]
### Current behaviour
![image](https://user-images.githubusercontent.com/27210994/64690804-dc39d680-d4c3-11e9-827a-dbfe18befe7a.png)
'initialRouteName' does not exist in type 'NavigationBottomTabOptions'

### Expected behaviour
no error

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios
| react-native          | 0.61.0
| react-navigation-tabs | 2.4.1
| node                  | 10.16.0
| npm or yarn           | 1.17.0

**Comment by EternalChildren** [comment]
Who can tell me the reason ? this lib is written by typescript. so the definition is auto generate ?

**Comment by EternalChildren** [comment]
@satya164 the latest version don't solve completely. 
![image](https://user-images.githubusercontent.com/27210994/64904132-01af2600-d6f8-11e9-9f55-d22e2d737847.png)
**tabBarOptions** still can't be recognized.

**Comment by Jakst** [comment]
There are more props that exist in the source code but not in types.

So far I've had problems with `tabBarComponent`, `tabBarOptions` and `lazy` on both `createBottomTabNavigator` and `createMaterialTopTabNavigator`. `swipeEnabled` also seems to be missing from `createMaterialTopTabNavigator`.

Autocompleting on config object of `createMaterialTopTabNavigator` or  `createBottomTabNavigator` only gives the following suggestions: 
```
backBehavior
defaultNavigationOptions
initialRouteName
initialRouteParams
navigationOptions
order
paths
resetOnBlur
```

As you can see, something seems to be very broken with the types on both tab creators.

Version: react-navigations-tabs@2.5.2
Example:
```javascript
const BottomNavigator = createBottomTabNavigator(tabs, {
  tabBarComponent: BottomTabComponent
})
```

> Argument of type '{ tabBarComponent: ({ getLabelText, jumpTo }: Props) => Element; }' is not assignable to parameter of type 'CreateNavigatorConfig<{}, NavigationTabRouterConfig, Partial<NavigationBottomTabOptions>, NavigationTabProp<NavigationRoute<NavigationParams>, any>>'.
>   Object literal may only specify known properties, and 'tabBarComponent' does not exist in type 'CreateNavigatorConfig<{}, NavigationTabRouterConfig, Partial<NavigationBottomTabOptions>, NavigationTabProp<NavigationRoute<NavigationParams>, any>>'.

**Comment by thepost** [comment]
I am also having this issue in the latest version. Detailed in issue #6308.

**Comment by EternalChildren** [comment]
It's still have some problems. the error picture is in issue https://github.com/react-navigation/react-navigation/issues/6308#issuecomment-532489518

**Comment by EternalChildren** [comment]
well, the generated Navigator is also not right.
```typescript
const Home = (props: NavigationProps) => {
  const { navigation } = props;

  return (
    <SafeAreaView>
      <Navigator navigation={navigation} />  // exist error
    </SafeAreaView>
  );
};
Home.router = Navigator.router;  // exist error
```
first error: 
2322: Type '{ navigation: NavigationScreenProp<NavigationRoute<{}>, NavigationParams>; }' is not assignable to type 'IntrinsicAttributes & { chi
ldren?: ReactNode; }'.  Property 'navigation' does not exist on type 'IntrinsicAttributes & { children?: ReactNode; }'.
second error:
2339: Property 'router' does not exist on type 'ComponentType<{}>'.  Property 'router' does not exist on type 'ComponentClass<{}, any>'.
@satya164

**Comment by xushuailing** [comment]
typeof createBottomTabNavigator // React.ComponentType<{}>;

However, createAppContainer requires a parameter of type `NavigationNavigator`；

```
const BottomTabNavigator = createBottomTabNavigator({
  user: UserPage,
  classify: ClassifyPage,
});

export default createAppContainer(BottomTabNavigator); // error
```

Parameters of type "ComponentType<{}>" cannot be assigned to parameters of type "NavigationNavigator<unknown, unknown>".
You cannot assign type "ComponentClass<{}, any>" to type "NavigationNavigator<unknown, unknown>".
Unable to assign type "ComponentClass<{}, any>" to type "ComponentClass<NavigationNavigatorProps<unknown, {}>, any> & {router: NavigationRouter<unknown, {}>; NavigationOptions? : unknown; } ".
Property 'router' is missing in type 'ComponentClass<{}, any>' but required in type '{router: NavigationRouter<unknown, {}>; NavigationOptions? : unknown; } 'ts (2345).


@satya164
