### ISSUE TITLE
swipeEnabled property not working in materialTopNavigator

### ISSUE THREAD

**Issue by gabrielyoto** [react-navigation/tabs#167]
Current Behavior

`const TabNavigator = createMaterialTopTabNavigator({`
    `Screen1,`
  `Screen1,`
`}, {`
  `swipeEnabled: true,`
`});`
- When I try to swipe between screens, it doesn't do anything

Here's the documentation
[https://reactnavigation.org/docs/en/material-top-tab-navigator.html#tabnavigatorconfig](https://reactnavigation.org/docs/en/material-top-tab-navigator.html#tabnavigatorconfig)

### My Environment

    "react": "16.8.6",
    "react-native": "0.60.5",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-reanimated": "^1.2.0",
    "react-navigation": "^4.0.0",
    "react-navigation-stack": "^1.5.3",
    "react-navigation-tabs": "^2.4.0"

**Comment by johman10** [comment]
Weird, I'm experiencing the same issue in my environment, but when I create an Expo it seems to work: https://snack.expo.io/Bk0Q5jwwr

**Comment by satya164** [comment]
Please follow the getting started guide and configure `react-native-gesture-handler`: https://reactnavigation.org/docs/en/getting-started.html

**Comment by johman10** [comment]
@satya164 thank you for your input. I checked that guide again, and did indeed miss something, but even if I add react-native-screen and add the two lines to my `android/app/build.gradle`. It doesn't seem to work.

**Comment by satya164** [comment]
@johman10 have you configured **`react-native-gesture-handler`**? please double-check and if it's still a problem, open an issue with a runnable demo in a GitHub repo.

**Comment by johman10** [comment]
@satya164 new issue opened with a reproduction repo.

**Comment by johman10** [comment]
Closed because @satya164 was correct after all.

To everyone having this issue please note that you even though you're on ReactNative 0.60+ you will still have to do the part staying "To finalize installation of react-native-gesture-handler" of the [getting started guide](https://reactnavigation.org/docs/en/getting-started.html)

**Comment by ShahidAli786** [comment]
check your [react-native-gesture-handler](https://kmagiera.github.io/react-native-gesture-handler/docs/getting-started.html) setup in MainActivity file. example here

```
package com.swmansion.gesturehandler.react.example;

import com.facebook.react.ReactActivity;
+ import com.facebook.react.ReactActivityDelegate;
+ import com.facebook.react.ReactRootView;
+ import com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView;

public class MainActivity extends ReactActivity {

  @Override
  protected String getMainComponentName() {
    return "Example";
  }

+  @Override
+  protected ReactActivityDelegate createReactActivityDelegate() {
+    return new ReactActivityDelegate(this, getMainComponentName()) {
+      @Override
+      protected ReactRootView createRootView() {
+       return new RNGestureHandlerEnabledRootView(MainActivity.this);
+      }
+    };
+  }
}
```
