### ISSUE TITLE
Supported styles for tabBarOptions

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/tabs#17]
Moved from https://github.com/react-navigation/react-navigation/issues/3675.

If we don't support a style type, we should warn maybe.

<hr />

### Current Behavior

- When trying to add margins to just the TabBar.js section, the Indicator does not take the margin into consideration.

### Expected Behavior

- When assigning a margin Horizontal for the indicator to reduce size further.

### How to reproduce

- Create a TabNavigator as such:
```
const Tab = TabNavigator(
  {
    First: {
      screen: FirstScreen,
    },
    Second: {
      screen: SecondScreen,
    },
    Third: {
      screen: ThirdScreen,
    },
  },
  {
    tabBarOptions: {
      style: {
        marginHorizontal: 50,
      },
...
```
- you should see that the indicator is larger than 1 cell of the tab.

Snack: https://snack.expo.io/Sylo40adM

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | ^1.1.1
| react-native     | 0.52.0
| node             | v9.4.0
| npm or yarn      | 4.6.1

**Comment by gamingumar** [comment]
I am stuck. Is there any solution available for this?

**Comment by brentvatne** [comment]
@gamingumar - i don't understand the question, this issue is about providing warnings for unsupported styles

**Comment by satya164** [comment]
I'll also accept PRs to react-native-tab-view to automatically handle it instead of warnings. Should be straightforward.

**Comment by gamingumar** [comment]
Is there a solution to somehow implement horizontal margin for tab view in react navigation? Currently indicator is causing issue when horizontal margin is applied.

**Comment by jarredwitt** [comment]
Had the overflowing indicator issue as well when applying a margin to a customer header that contained a TabBar component. Was able to fix it using by modifying the layout prop that is passed to the header. Basically: 

```
<TabBar
  layout={{
    ...otherProps.layout,
    width: deviceWidth - (someMargin * 2),
  }}
/>
```

Got the idea from this issue https://github.com/react-native-community/react-native-tab-view/issues/216#issuecomment-341186872

**Comment by satya164** [comment]
Closing since width, margin etc are handled now.
