### ISSUE TITLE
createMaterialTopTabNavigator can't switch tabs on web

### ISSUE THREAD

**Issue by christianjuth** [react-navigation/tabs#170]
### Current behaviour

createMaterialTopTabNavigator is able to create the navigator on web using `@react-navigation/web`. Navigator renders the default tab currently (occationaly bugging out), but when I click on any of the other tabs nothing happens. When I check the Javascript console I see the following error.

```
Reanimated: createNode is unimplemented on web
Reanimated: connectNodes is unimplemented on web
```

I'm not sure if this is an issue with react-navigation, react-native-reanimated, or react-native-web. Is anyone else seeing this issue?

### Expected behaviour

Tabs should work the same as they do on iOS and Android. When I click on a tab it should navigate to and render that screen.

### Code sample

Here are parts of my code. The full project can be found in [this repo](https://github.com/christianjuth/rutgram).

File: navigation/MainTabNavigator.js
```javascript
const LikesStack = createMaterialTopTabNavigator({
  Following: {
    screen: FollowingScreen,
    path: 'following',
  },
  You: {
    screen: YouScreen,
    path: 'you',
  }
}, config);
LikesStack.navigationOptions = {
  tabBarIcon: ({ focused }) => (
    <Icon size={30} name={'heart' + (focused ? '' : '-o')}/>
  ),
};
LikesStack.path = 'likes';

const tabNavigator = createBottomTabNavigator({
  HomeStack,
  SearchStack,
  CameraStack,
  LikesStack,
  ProfileStack
}, {
  tabBarOptions: {
    showLabel: false
  }
});
tabNavigator.path = 'app';

export default tabNavigator;
```

File: navigation/AppNavigator.web.js
```javascript
const switchNavigator = createSwitchNavigator({
  // Authentication set up as suggested by
  // https://reactnavigation.org/docs/en/auth-flow.html
  App: MainTabNavigator
});
switchNavigator.path = '';

export default createBrowserApp(switchNavigator);
```

### Screenshots (if applicable)

![screen shot](https://media.giphy.com/media/Wq2qvZ6jKTaGFWLg4k/giphy.gif)

### What have you tried

I tried updating all related packages to the latest version, including: react-native-reanimted, react-navigation, @react-navigation/web, react-navigation-tabs, expo

### Your Environment

| software              | version
| --------------------- | -------
| platform        | react-native-web ^0.11.7 (setup with expo) 
| expo                      | sdk 34
| react-native          | https://github.com/expo/react-native/archive/sdk-34.0.0.tar.gz
| react-navigation-tabs | ^2.4.0
| react-native-reanimated | ^1.2.0
| @react-navigation/web | ^1.0.0-alpha.9
| node                  | v12.5.0
| npm           | 6.11.3

**Comment by christianjuth** [comment]
I just tested the issue using Expo SDK 35 and tabs are still not working in the browser.

**Comment by coats707** [comment]
I have this issue as well, but with the drawer navigation.

**Comment by benceg** [comment]
My workaround has been to downgrade to React Navigation 3.x.
It's not ideal, but it does fix the issue for now.
In doing so, you'll render the `react-navigation-tabs` and `react-navigation-stack` packages redundant and so may as well remove them from your bundle.
More recent iterations of some of React Navigation's underlying components (e.g. `react-native-tab-view`) rely heavily on `react-native-gesture-responder`, which is not fully implemented for web.

**Comment by satya164** [comment]
> My workaround has been to downgrade to React Navigation 3.x.

You don't need to downgrade. You can skip upgrading the navigators and install the same versions of navigators used by react-navigation 3 asper release notes https://github.com/react-navigation/react-navigation/releases/tag/v4.0.0

**Comment by benceg** [comment]
> You don't need to downgrade. You can skip upgrading the navigators and install the same versions of navigators used by react-navigation 3 as per release notes https://github.com/react-navigation/react-navigation/releases/tag/v4.0.0

Thanks for responding so promptly @satya164. Unfortunately the TypeScript caveat applies to me:

> If you're using TypeScript, you'll also need to upgrade the navigators to the latest version following the previous section.

I've edited my comment above to reflect this.

**Comment by lovetofail** [comment]
I've tried this PR and it works on web. No more "Reanimated" warnings and I'm able to open/close drawer with my mouse. Special thanks to @EvanBacon. 
https://github.com/kmagiera/react-native-reanimated/pull/390
