### ISSUE TITLE
focused prop tabBarIcon strange behaviour 

### ISSUE THREAD

**Issue by rossjohnsonMP** [react-navigation/tabs#171]
### Current behaviour

When navigating to a tab the focused prop is passed through as true and then again as false wether the tab is being focused on or not

### Expected behaviour

TabBarIcon only re-rendered once with true if focused or false if not focused

### Code sample

https://github.com/rossjohnsonMP/Recipe

As can be seen in the code sample - any behaviour toggled by focused (text color) seems to work fine but console logging the prop shows it doesn't have the correct value which is stopping me from being able to add a side effect to the tab being focused or unfocused 

### What have you tried

console logging the prop - switching behaviour within the component on the prop

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios
| react-native          | 0.59.8 and 0.60.5
| react-navigation-tabs | 2.4.1
| node                  | 12.10
| npm or yarn           | yarn - 1.15.2

**Comment by hejun041** [comment]
you can try this [https://github.com/react-navigation/tabs/pull/179](url)
may help

**Comment by satya164** [comment]
This is expected behaviour. `tabBarIcon` is not the place to do side-effects. Please use focus events: https://reactnavigation.org/docs/en/navigation-events.html

**Comment by rossjohnsonMP** [comment]
@satya164 but why does the `tabBarIcon` get passed the prop `focused` if it doesn't hold the value you'd expect?

I tried Navigation events but Blur isnt fired when I navigate between tabs. The tab itself is in focus but the screen that is shown when the tab is active is not in focus. hope that makes sense.

**Comment by satya164** [comment]
You can check the code to see why this is the case. The `focused` prop is meant to render how the icon will look in focus state, not for side effects.

**Comment by rossjohnsonMP** [comment]
https://github.com/react-navigation/tabs/blob/master/src/views/CrossFadeIcon.tsx#L39 - I see - maybe theres something wrong with the animation because thats kind of what I'm trying to achieve. but it looks to me like the focused icon disappears and the unfocused icon appears instantly
