### ISSUE TITLE
How should I set the header in ‘createBottomTabNavigator’?

### ISSUE THREAD

**Issue by caro-li** [react-navigation/tabs#178]
### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | ios
| react-native          | 0.60.5
| react-navigation-tabs | 2.5.2
| node                  |
| npm or yarn           |

**Comment by tsurumure** [comment]
the same issue here.

**Comment by satya164** [comment]
Use a custom header component.

**Comment by tsurumure** [comment]
> Use a custom header component.

thanks. but why `navigationOptions` is not work?

**Comment by satya164** [comment]
Because header is part of stack navigator, not tab navigator.
