### ISSUE TITLE
Cannot read property 'configureProps' of undefined

### ISSUE THREAD

**Issue by ghmeec** [react-navigation/tabs#183]
this happens when importing  

import {createMaterialTopTabNavigator} from 'react-navigation-tabs'

and i followed all set up instructions

react-navigation-tabs@^2.5.5,

**Comment by nageshbf** [comment]
@ghmeec I am facing same problem. If you found solution please let me know.

**Comment by satya164** [comment]
Install and link reanimated as mentioned in getting started guide: https://reactnavigation.org/docs/en/getting-started.html

**Comment by kojongDev** [comment]
In android my case I just got an error with install and link. If you sync later, it will be solved.
