### ISSUE TITLE
Getting Invariant Violation: Native Module cannot be null after installing dependencies

### ISSUE THREAD

**Issue by parthpatel20010** [react-navigation/tabs#197]
### Current behaviour

After installing react-native-reanimated, I get an "Invariant violation: Native module cannot be null" error. 

### Code sample

I followed the advice of others with the same error and added the following to package.json:
  "jest": {
    "preset": "react-native",
    "SetupFiles": [
      "test/setup.js"
    ]
  }

and my setup.js file looks like this:

jest.mock('react-native-reanimated', () => {
  return {
    addEventListener: jest.fn(),
    removeEventListener: jest.fn(),
    openURL: jest.fn(),
    canOpenURL: jest.fn(),
    getInitialURL: jest.fn(),
  }
})

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        |
| react-native          |
| react-navigation-tabs |
| node                  |
| npm or yarn           |

**Comment by eddskt** [comment]
In my case i solved the problem with:
1 - react-native link
2 - cd ios
3 - pod install
4 - cd ..
4 - watchman watch-del-all; rm -rf $TMPDIR/react-native-packager-cache-*; rm -rf $TMPDIR/metro-bundler-cache-*; rm -rf node_modules/; npm cache clean --force; npm install; npm start

**Comment by ralph-dev** [comment]
Yes, you have a library that has not been properly linked to your react native app. Please review each library or comment out the import statements to identify which library it is.
