### ISSUE TITLE
After hidden bottom tab bar by open keyboard remains white block

### ISSUE THREAD

**Issue by fri0z** [react-navigation/tabs#206]
### Current behaviour
After hidden bottom tab bar by open keyboard remains white block. I use mode `android:windowSoftInputMode="adjustResize"` and `adjustResize` fits most to me. I tried other modes and not fits me.

### Expected behaviour

I expect to hide the white bar in adjustResize mode

### Code sample

```
import React from 'react';
import { Input } from "react-native-elements";
import { View, ScrollView } from 'react-native';

class Example extends React.Component {
    render() {
        return (
            <View style={ { backgroundColor: '#ccc', flex: 1 } }>
                <ScrollView>
                    <Input
                        label={ 'Серия бланка' }
                        placeholder='Серия бланка'
                    />
                </ScrollView>
            </View>
        );
    }
}
```

### Screenshots (if applicable)

![photo_2019-10-24_20-37-34](https://user-images.githubusercontent.com/1527987/67505173-34a7ea80-f6a4-11e9-9f61-e619828d6596.jpg)

### What have you tried
I watched #16 / #64 

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | android
| react-native          | 0.60.5
| react-navigation-tabs | 4.0.10
| react-navigation-stack | 1.10.2
| react-navigation-tabs | 2.5.6
| node                  | v10.17.0
| npm or yarn           | 6.11.3

**Comment by GuilhermeFM** [comment]
Facing the same problem.

When we set the keyboardHidesTabBar property to true the bottom bar animates and disappears leaving a white bar in its place.

**Comment by yasirwahid** [comment]
i changed to android:windowSoftInputMode="adjustPane" and the white bar was gone ,but not a feasible solution to me i also need to work on "adjustResize" mode

**Comment by fri0z** [comment]
Is there any information on this issue?

**Comment by wwgoncalves** [comment]
@fri0z Facing the same here, trying to figure things out... 
It seems to occur because the hide animation (tab bar resizing) is much fast -- and the Android app "root view" background is white.

I've managed to come up with a workaround that recreates the hide animation. See if it's useful for you:
```
import React, { useEffect } from 'react';
...
import { Keyboard, Animated } from 'react-native';

const animatedOpacity = new Animated.Value(1.0);
const animatedHeight = new Animated.Value(49);
...
...
 useEffect(() => {
    const keyboardDidShowListener = Keyboard.addListener(
      'keyboardDidShow',
      () => {
        Animated.timing(animatedOpacity, {
          toValue: 0.0,
          duration: 200,
        }).start();
        Animated.timing(animatedHeight, { toValue: 0, duration: 500 }).start();
      }
    );

    const keyboardDidHideListener = Keyboard.addListener(
      'keyboardDidHide',
      () => {
        Animated.timing(animatedOpacity, {
          toValue: 1.0,
          duration: 800,
        }).start();
        Animated.timing(animatedHeight, { toValue: 49, duration: 300 }).start();
      }
    );

    return function cleanup() {
      keyboardDidShowListener.remove();
      keyboardDidHideListener.remove();
    };
  }, []); // eslint-disable-line
...
...
ScreenFunctionalComponentName.navigationOptions = {
  ...
  tabBarOptions: {
    ...
    keyboardHidesTabBar: false,
    ...
    style: {
      ...
      opacity: animatedOpacity,
      height: animatedHeight,
      ...
    },
  },
};
```

**Note:** You will probably still see a white background while the animation occurs. To make things look better we have to change the app "root" background. Inside the folder `android/app/src/main/res/values`, create the file `colors.xml` with a reference for your custom color, e. g.
```
<resources>
  <color name="windowBackgroundColor">#cccccc</color>
</resources>
```
and add the following line to the `android/app/src/main/res/values/styles.xml` file referring your color just below the last `item`:
```
        <item name="android:windowBackground">@color/windowBackgroundColor</item>
```

**Comment by fri0z** [comment]
@wwgoncalves Thanks for the hint, but this is only a temporary solution to the problem.

**Comment by fri0z** [comment]
Today I tested the fixes that @vonovak suggested and they work. Waiting for the adoption of corrections.
