### ISSUE TITLE
Significant performance issue with createMaterialTopTabNavigator

### ISSUE THREAD

**Issue by James-E-Adams** [react-navigation/tabs#207]
### Current behaviour

Using `createMaterialTopTabNavigator` from `react-navigation-tabs`, the performance is bad and gets linearly(?) worse the more tabs you add. Switching out to `createBottomTabNavigator` fixes it (and I've isolated all our custom code out from the navigation).The most noticeable frame rate drop is when clicking a tab. Swiping seems fine. Please let me know if this issue should be better opened here https://github.com/react-navigation/tabs/. 

### Expected behaviour

No perf issue changing tabs. 

### Code sample

http://snack.expo.io/ByGEdWScB

### What have you tried

Isolated to createMaterialTopTabNavigator. Switching from createMaterialTopTabNavigator to createBottomTabNavigator fixes it.

### Related Issues
https://github.com/react-navigation/react-navigation/issues/6359

Let me know if I should migrate this issue to the one above. 

### Your Environment

| software              | version
| --------------------- | -------
| ios or android        | both
| react-native          | 0.61.2
| react-navigation-tabs | ^2.5.6
| node                  | 10.16.3
| npm or yarn           | yarn

**Comment by satya164** [comment]
Please provide full repro. The snack doesn't have any perf issues (tried on the appetize simulator as well as real device).

**Comment by James-E-Adams** [comment]
Sorry I thought that snack showed the issue. It's the same as shown in the gif here: https://github.com/react-navigation/react-navigation/issues/6359

I'll see if I can repro it properly after work hours, but for now I've downgraded `react-navigation-tabs` to `1.2.0` after realising it's not a pre-req to upgrade to v2 to use react-navigation v4.
