### ISSUE TITLE
the performance of MaterialTopTabNavigator is slow

### ISSUE THREAD

**Issue by LeeMoonki** [react-navigation/tabs#210]
### Current Behavior

(I only test all in adroid.)

![sample_video](https://user-images.githubusercontent.com/20311378/66249308-2b45f500-e76c-11e9-9d88-42614c92596f.gif)

I faced the performance issue of MaterialTopTabNavigator. And I found that the performance issue is came from itself not from its screen rendering performance or others.

When I just replace the `MaterialTopTabNavigator` with `BottomTabNavigator`, there is no performance issue anymore. i.e, the `BottomTabNavigator` has same screen as `MaterialTopTabNavigator` but much faster than it.

Additionally, when I use `MaterialTopTabNavigator` the screen is rendered very slowly. Also, when I use `BottomTabNavigator` the speed of rendering of screen is very fast.

Lastly, the speed is also differed between virtual device and real device. In virtual device the rendering speed is slower than real device but the navigator is work better in the virtual device. (In virtual device, if I press the tab, the animation and rendering screen is slow but act right after. But in real device, if I press the tab, after few seconds the animation and rendering screen is triggered)

Why the difference is occurred ?

The following is my code. 

```
import React from 'react';
import {View, Text, StyleSheet} from 'react-native';
import {createMaterialTopTabNavigator} from 'react-navigation-tabs';

import {GROUPS} from '../../../config';
import navStyle, {labelStyle} from '../../../styles/memberNavigator';

import MainScreen from '../../../screens/feed/MainScr';

const group = GROUPS.groupA;
const styles = StyleSheet.create(navStyle);
const lstyles = StyleSheet.create(labelStyle);

class TabBarLabel extends React.Component {
  static lastFocused = null;
  constructor(props) {
    super(props);
  }
  render() {
    return this.props.focused ? (
      <View style={lstyles.container_focused}>
        <Text style={lstyles.label_focused}>{this.props.name}</Text>
      </View>
    ) : (
      <View style={lstyles.container_blur}>
        <Text style={lstyles.label_blur}>{this.props.name}</Text>
      </View>
    );
  }
}

const memberNavigationConfig = (function() {
  const result = {};

  for (const member of group.members) {
    result[member.id] = {
      screen: MainScreen,
      navigationOptions: function({navigation}) {
        return {
          title: member.name,
          tabBarLabel({focused, horizontal, tintColor}) {
            return <TabBarLabel focused={focused} name={member.name} />;
          },
          tabBarOnPress(payload) {
            console.log('tabBarOnPress : ', member.name);
            payload.navigation.setParams({group: group, member: member});
            payload.defaultHandler();
          },
        };
      },
    };
  }

  return result;
})();

const FeedAGroupMemberNavigator = createMaterialTopTabNavigator(
  {
    ...memberNavigationConfig,
  },
  {
    initialRouteName: group.members[0].id,
    swipeEnabled: false,
    tabBarOptions: {
      scrollEnabled: true,
      ...styles,
    },
  },
);

export default FeedAGroupMemberNavigator;

```

And I already update all related packages.

### Expected Behavior

- rendering screens and animation of tab is fast like other navigators.

### How to reproduce

- I run above code under environment written below.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.12.1
| react-navigation-tabs      | 2.5.5
| react-native-tab-view      | 2.10.0
| react-native     | 0.60.5
| node             | 10.13.0
| npm or yarn      | 6.4.1

**Comment by yelkamel** [comment]
same issue here

**Comment by kkorezelidis** [comment]
i can reproduce the issue even with the latest version

"react-native": "0.61.4",
"react-navigation-tabs": "2.7.0",
"react-navigation": "4.0.10",
"react-navigation-stack": "1.10.3",
 "react-navigation-tabs": "2.7.0",
