### ISSUE TITLE
When I import createBottomTabNavigator, It shows error

### ISSUE THREAD

**Issue by giva9712** [react-navigation/tabs#237]
When I import 
```
import { createBottomTabNavigator } from "react-navigation-tabs";
```

**It shows error:**
Unsupported node type: param
createNode
NodesManager.java:40

I am using React Native Expo.

**Comment by satya164** [comment]
Upgrade `react-native-reanimated` to the latest version.

```js
yarn add react-native-reanimated
```

**Comment by giva9712** [comment]
My dependicies are:
```json
"expo": "^35.0.0",
    "react": "16.8.3",
    "react-dom": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-gesture-handler": "^1.5.3",
    "react-native-reanimated": "^1.7.0",
    "react-native-safe-area-context": "^0.6.2",
    "react-native-screens": "1.0.0-alpha.23",
    "react-native-vector-icons": "^6.6.0",
    "react-native-web": "^0.11.7",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^2.0.15",
    "react-navigation-tabs": "^2.7.0",
    "react-redux": "^7.1.3",
    "redux": "^4.0.5",
    "redux-thunk": "^2.3.0"
```
It has already updated but it still shows

**Comment by satya164** [comment]
You can try downgrading it to `1.4.0` then.

**Comment by Prernapundir** [comment]
I m getting same error but still not resolved??

**Comment by pieronoviello** [comment]
Same error here

**Comment by gabrielste1n** [comment]
i also have the same error

**Comment by Prernapundir** [comment]
> i also have the same error

My error resolved when i downgrade the version of react-native-reanimated@1.4.0....just try this...and refresh the cache memeory...restart your app

**Comment by iamhassanraza** [comment]
> When I import
> 
> ```
> import { createBottomTabNavigator } from "react-navigation-tabs";
> ```
> 
> **It shows error:**
> Unsupported node type: param
> createNode
> NodesManager.java:40
> 
> I am using React Native Expo.

its an exception by react-native-reanimated. 
i am getting the same error, have your resolved it yet?

**Comment by gabrielste1n** [comment]
> > When I import
> > ```
> > import { createBottomTabNavigator } from "react-navigation-tabs";
> > ```
> > 
> > 
> > **It shows error:**
> > Unsupported node type: param
> > createNode
> > NodesManager.java:40
> > I am using React Native Expo.
> 
> its an exception by react-native-reanimated.
> i am getting the same error, have your resolved it yet?

Yes, the downgrade to react-native-reanimated@1.4.0 worked for me, it is import to clear expo cache with "expo r -c".
