### ISSUE TITLE
Wrong types for NavigationBottomTabScreenComponent

### ISSUE THREAD

**Issue by nmpribeiro** [react-navigation/tabs#239]
**Current Behavior**

- What code are you running and what is happening?
```
type Params = { userId: string };
type ScreenProps = { arg1: string };
const DeckScreen: NavigationBottomTabScreenComponent<Params, ScreenProps> = (
    props
) => {
   console.log(props.screenProps) // returns undefined but it's what types specify
   console.log(props.arg1) // returns 'hello world' but vscode gives error based on types
   return (<View><Text>{props.arg1}</Text></View>)
}
```

**Expected Behavior**

- What do you expect should be happening?
I expected types to be correct for FunctionalComponents. The culprit line would be the following (in types.d.ts from `react-navigation-tabs`):
```
export declare type NavigationTabScreenProps<Params = NavigationParams, ScreenProps = unknown> = {
    theme: SupportedThemes;
    navigation: NavigationTabProp<NavigationRoute, Params>;
    screenProps: ScreenProps;
};
```

**Your Environment**

| software                     | version |
     "react-navigation": "^4.0.10",
    "react-navigation-hooks": "^1.1.0",
    "react-navigation-stack": "^2.0.2",
    "react-navigation-tabs": "^2.6.2",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "expo": "~36.0.0",
| node                         | v12.14.1
| npm or yarn                  | 6.13.4

**Comment by nmpribeiro** [comment]
I have set a local type to fix this:
```
export declare type MyNavigationTabScreenProps<
    Params = NavigationParams,
    ScreenProps = unknown
> = ScreenProps & {
    theme: SupportedThemes;
    navigation: NavigationTabProp<NavigationRoute, Params>;
};
export declare type MyNavigationBottomTabScreenComponent<
    Params = NavigationParams,
    ScreenProps = unknown
> = React.ComponentType<MyNavigationTabScreenProps<Params, ScreenProps>> & {
    navigationOptions?: NavigationScreenConfig<
        NavigationBottomTabOptions,
        NavigationTabProp<NavigationRoute, Params>,
        ScreenProps
    >;
};
```

**Comment by satya164** [comment]
> returns 'hello world' but vscode gives error based on types

You are specifying the type, so it's up-to you to make sure that the types are correct. Without repro I cannot say what's wrong, but `screenProps` are never passed as normal props. If you're specifying the type on a screen component, then they will be correct.

**Comment by nmpribeiro** [comment]
@satya164 I couldn't follow your logic, but perhaps I can as you then, why this:
```
interface MyCompArgs {
   myProp: string;
}
const myComp: NavigationTabScreenProps<RouteParams, MyCompArgs> = props => {
   const myString = props.screenProps.myProp;
   return <View><Text>My passed string: {myString}</Text></View>
}
```
would be the case? What's the reasoning for it?
Why not `props.myProp` directly?
Also, I do not see why Screen components would need to be different from regular components. But since I set my own types already (and if someone bumps into the same issue/confusion), at least check the type from my comment above: https://github.com/react-navigation/tabs/issues/239#issuecomment-576593720
