### ISSUE TITLE
tabPress listener not working when wrapped in Stack.Navigator

### ISSUE THREAD

**Issue by dblazeski** [react-navigation/tabs#250]
**Current Behavior**

The listener for `tabPress` event is not working when the screen component is an instance of Stack.Navigator. Works fine when the screen component is an instance of Stack.Screen.

**Expected Behavior**

The 'tabPress' listener to fire.

**How to reproduce**

Expo - https://snack.expo.io/@slusatel/react-navigation-tabpress
1st tab works fine with direct Stack.Screen component.
2nd tab fails - with Stack.Navigator component.

**Your Environment**

| software                     | version |
| ---------------------------- | ------- |
| Platform               | iOS
| react-navigation             | 5.0.3
| react-navigation-tabs        | 5.0.3
| react-native-reanimated      | 5.0.3
| react-native-gesture-handler | 5.0.3
| react-native-screens         | master
| react-native                 | latest
| expo                         |
| node                         | latest
| npm or yarn                  | latest

**Comment by WoLewicki** [comment]
Is this what you mean? https://reactnavigation.org/docs/en/nesting-navigators.html#nested-navigators-dont-receive-parents-events

**Comment by dblazeski** [comment]
🤦🏻‍♂️Missed it.
Thanks @WoLewicki
