### ISSUE TITLE
contentInsetAdjustmentBehavior automatic not applied on ScrollView in tab screen

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/tabs#37]
### Current behaviour

Not being applied, so safe areas are being ignored.

### Expected behaviour

Should behave the same in tab as it does outside of a tab.

### Code sample

https://snack.expo.io/H1_oI9Wf7

### What have you tried

I tried the same screen component within a stack and it applied the insets as expected. I also tried it on its own, without any navigation, and got the same result as in stack.

### Your Environment

react-navigation@2.5.4 and react-native 0.55.4

**Comment by scottahaynie** [comment]
Any update on this issue?  Or at least a workaround?

**Comment by ericvicenti** [comment]
I guess we need an iPhone X in order to reproduce this? Hard for people to fix if they can't reproduce without a specific expensive device 😞

**Comment by brentvatne** [comment]
not that i know of. PR welcome, not working on this right now
