### ISSUE TITLE
Navigating to specific route in MaterialTopTabNavigator within a StackNavigator often leads to the first route defined on iOS

### ISSUE THREAD

**Issue by Transfusion** [react-navigation/tabs#75]
EDIT: Seems to occur on iOS only, tested with iPhone X 12.1 simulator
### Current Behavior

`MainStackNavigator.js`:
```js
export const MainStackNavigator = createStackNavigator({
  HomeScreen: {screen: HomeScreen},
  FaultyTabNavigator: {screen: FaultyTabNavigator},
  WorkingTabNavigator: {screen: WorkingTabNavigator}
}, {
  initialRouteName: 'HomeScreen'
});
```
`FaultyTabNavigator.js`:
```js
export const FaultyTabNavigator = createMaterialTopTabNavigator({
  FTab1: {screen: TabbedScreen1},
  FTabWithScreenInName: {screen: TabbedScreen2},
  FAnotherScreen: {screen: TabbedScreen3},
  FLastPage: {screen: TabbedScreen4}
}, ... );
```

`this.props.navigation.navigate('FTabWithScreenInName')` in `HomeScreen` is unpredictable, randomly navigating to `FTab1` or `FTabWithScreenInName`.

[Link to .gifv of issue on imgur](https://i.imgur.com/MGqikv0.gifv)

### Expected Behavior

Doing `this.props.navigation.navigate('RouteName')` should always navigate to `RouteName`.

### How to reproduce

[https://snack.expo.io/@transfusion/inconsistent-materialtoptabnavigator](https://snack.expo.io/@transfusion/inconsistent-materialtoptabnavigator)

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.5, occurs with 3.0.6 too
| react-native     | Occurs with 0.57.7 outside expo too
| node             | 10.8.0
| npm or yarn      | 6.2.0

**Comment by brentvatne** [comment]
cc @satya164

**Comment by sregg** [comment]
any news on this?
I'm seeing this with `react-navigation: 3.8.1` and `react-native: 0.59`

**Comment by brentvatne** [comment]
i recommend using react-navigation-tabs@^2.0.0, you can install it on its own an import the navigator from there instead and it'll resolve the issue for you. note that it requires you have react-native-reanimated installed

**Comment by sregg** [comment]
I'm getting this error with `react-navigation-tabs@^2.0.0` and `react-native-reanimated@^1.0.0`:

```
TypeError: position.interpolate is not a function. (In 'position.interpolate({
          inputRange: inputRange,
          outputRange: outputRange
        })', 'position.interpolate' is undefined)

This error is located at:
    in TabBarItem (at TabBar.js:336)
```

**Comment by sregg** [comment]
I temporarily fixed the issue without `react-navigation-tabs` but by setting `swipeEnabled: false, animationEnabled: false`

**Comment by brentvatne** [comment]
do you have a custom tab view or something? can you post a repro?

**Comment by sregg** [comment]
I couldn't reproduce in a snack. 
re: the `position.interpolate is not a function` error with `react-navigation-tabs`, that seems to be related to: https://github.com/react-native-community/react-native-tab-view/issues/738

**Comment by earlyCloud** [comment]
I'm getting this error too ):

TypeError: undefined is not a function (evaluating 'position.interpolate({ 
          inputRange: inputRange,
          outputRange: outputRange
        })')
This error is located at:
   in TabBarItem (at TabBar.tsx:396)

react-navigation-tabs@^2.1.3 and react-native-reanimated@^1.2.0

**Comment by davidli3100** [comment]
@earlyCloud same issue. Maybe try turning off swiping and animations for now?

**Comment by earlyCloud** [comment]
@davidli3100 I'm not sure. Maybe the wrong dependence (react-native-reanimated I guess) causes this, I reset my installed dependences and it works. I don't even know why it works now : ) 
May it help

**Comment by basha777** [comment]
> @davidli3100 I'm not sure. Maybe the wrong dependence (react-native-reanimated I guess) causes this, I reset my installed dependences and it works. I don't even know why it works now : )
> May it help

@earlyCloud did you change the version? even i am facing the same issue.

**Comment by SourceCipher** [comment]
Same here.. I was using this library couple of weeks ago and then upgraded to `react-native: "0.60.5"` and I forgot to install this library, but after noticing that my tab state change is super slow I remembered to install `react-navigation-tabs` to fix this issue but as soon as I did I got the same error as @sregg 

Seems like its smth within this library itself as all of my animations works fine (I disabled them all just to test it) and I am importing `Animated` from react-native and not reanimated which I think whats breaking this

**Comment by davidli3100** [comment]
> @davidli3100 I'm not sure. Maybe the wrong dependence (react-native-reanimated I guess) causes this, I reset my installed dependences and it works. I don't even know why it works now : )

@earlyCloud what do you mean by resetting dependencies?
