### ISSUE TITLE
[Bug] tabBarOnPress is called on whole screen

### ISSUE THREAD

**Issue by kesha-antonov** [react-navigation/tabs#84]
Hey!
I have 4 tabs with bottom tabbar.
I've provided ```tabBarOnPress``` to ```createBottomTabNavigator```

```tabBarOnPress``` gets called when I touch any area of the scene. Usually with first tab in params

### Expected Behavior

```tabBarOnPress``` should be called only when press tab - not scene,

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.9
| react-native     | 0.57.8
| node             | 10.13.0
| yarn      | 1.12.3

**Comment by satya164** [comment]
Can you provide a repro? @kesha-antonov

**Comment by emilioicai** [comment]
I'm facing this same issue. The problem doesn't show immediately but after some usage, pressing any touchable (or even empty parts of the screen) results in calling `tabBarOnPress`. If I close the simulator and reopen it everything goes back to normal for a while.

**Comment by emilioicai** [comment]
oddly enough, the `tabBarLabel` trick works

**Comment by satya164** [comment]
Closing because no repro was provided
