### ISSUE TITLE
How to get the height of bottom navigator?

### ISSUE THREAD

**Issue by iwantooxxoox** [react-navigation/tabs#97]
I'm trying to get the height of the bottom tab bar so that I know how to absolutely position a component above it without that component being cut off.

**Comment by brentvatne** [comment]
@satya164 - maybe useful for material-bottom-tabs and top-tabs too

**Comment by satya164** [comment]
I think currently if you use the `TopTabBar` component etc. and pass `onLayout` prop it should work to get the height. If not we should support it :)

Regarding the use case of getting the height for positioning something above it, I'd advise against that because layout is async, so whatever you want to render won't be rendered correctly before the callback is called. I'd do something like:

```js
tabBarComponent: props => (
  <View>
    <SomethingAbsolute />
    <TopTabBar {...props} />
  </View>
);
```

**Comment by brentvatne** [comment]
> Regarding the use case of getting the height for positioning something above it, I'd advise against that because layout is async, so whatever you want to render won't be rendered correctly before the callback is called. 

I think in the worst case where you want the tab bar and the overlay to be rendered at the same time there will be a frame or so of delay, wouldn't be ideal yeah. If you're going to animate it in or show it at any time after the initial render of the tab bar it's not a bad compromise though

**Comment by draperunner** [comment]
Found a way to solve this, using `onLayout` and `measureInWindow`, which seems to work fairly consistently on different Android devices and iPhones. It's a bit hacky and involves Redux. If you could find a simpler way to support this, that would be great! :D 

I created the following connected TabBar component. I could not pass `onLayout` directly to BottomTabBar, so I wrapped it in a View.

```
import React, { Component } from 'react';
import { connect } from 'react-redux';
import { View } from 'react-native';
import { BottomTabBar } from 'react-navigation';

class TabBarComponent extends Component {
  measure = () => {
    if (this.tabBar) {
      this.tabBar.measureInWindow(this.props.setTabMeasurement);
    }
  }

  render() {
    return (
      <View
        ref={(el) => { this.tabBar = el; }}
        onLayout={this.measure}
      >
        <BottomTabBar {...this.props} />
      </View>
    );
  }
}

function mapDispatchToProps(dispatch) {
  return {
    setTabMeasurement: (x, y, width, height) => dispatch({
      type: 'SET_TAB_MEASUREMENT',
      measurement: {
        x, y, width, height,
      },
    }),
  };
}

export default connect(null, mapDispatchToProps)(TabBarComponent);
```

I could then access the layout/measurement in the absolutely positioned component through the Redux state, and calculate its y position (`top`) with the formula `measurement.y - measurement.height - <height of component> - <desired margin to tab bar>`

**Comment by donholly** [comment]
@draperunner Thanks a lot for posting this solution! I was trying to avoid having to duplicate this logic everywhere that needed the TabBar height for keyboard avoidance calculations. While I'd really like to see this make its way into the library, this is a pretty good solution for keeping track of the state of the Tab Bar's dimensions for now. I'll Likely end up doing the same thing to get the height of the HeaderBar for Stack Navigators.

Thanks again!

**Comment by JanithaR** [comment]
@brentvatne 

> so this is not something that you probably want to actually handle yourself. i think it is worth adding an option to the tab navigator that allows you to pass in a callback for when the height is available / when it changes.

Is there an ETA on this?

**Comment by brentvatne** [comment]
no

**Comment by tungduonghgg123** [comment]
"How could you @brentvatne . You have the map to the haven and never show us the way."
Why don't you just provide us a method to get the height and position of of Bottom Tab Bar? You probably  know it because the Tab Bar need it to show up.

**Comment by mjmaix** [comment]
@draperunner I rewrote your solution using React Context


```TabBarComponent.tsx

import React, { Component } from 'react';
import { View, LayoutChangeEvent, LayoutRectangle } from 'react-native';
import { BottomTabBar, BottomTabBarProps } from 'react-navigation';

interface State {
  layout: LayoutRectangle;
}

const initialValue = {
  x: 0,
  y: 0,
  width: 0,
  height: 0,
};

const TabBarContext = React.createContext<LayoutRectangle>(initialValue);
export const TabBarProvider = TabBarContext.Provider;
export const TabBarConsumer = TabBarContext.Consumer;

class TabBarComponent extends Component<BottomTabBarProps, State> {
  public readonly state = {
    layout: initialValue,
  };
  private setTabMeasurement = (event: LayoutChangeEvent) => {
    const {
      nativeEvent: { layout },
    } = event;
    this.setState({
      layout,
    });
  };

  public render() {
    return (
      <TabBarProvider value={this.state.layout}>
        <View onLayout={this.setTabMeasurement}>
          <BottomTabBar {...this.props} />
        </View>
      </TabBarProvider>
    );
  }
}

export { TabBarComponent };

```

```TabBarAwareScrollView.tsx
import React, { ReactNode } from 'react';
import { ScrollView, ScrollViewProps } from 'react-native';
import { TabBarConsumer } from './TabBarComponent';

export const TabBarAwareScrollView = ({
  children,
  ...props
}: ScrollViewProps & { children: ReactNode }) => {
  return (
    <TabBarConsumer>
      {tabBarLayout => (
        <ScrollView
          {...props}
          contentContainerStyle={{
            paddingBottom: tabBarLayout.height,
          }}
        >
          {children}
        </ScrollView>
      )}
    </TabBarConsumer>
  );
};

```
<img width="150" alt="Screen Shot 2019-05-29 at 5 54 29 PM" src="https://user-images.githubusercontent.com/1903059/58548106-43948900-823b-11e9-8065-c085db7fee6e.png">
<img width="150" alt="Screen Shot 2019-05-29 at 5 54 26 PM" src="https://user-images.githubusercontent.com/1903059/58548104-42fbf280-823b-11e9-9697-89c6c9aa17aa.png">
<img width="150" alt="Screen Shot 2019-05-29 at 5 54 36 PM" src="https://user-images.githubusercontent.com/1903059/58548105-43948900-823b-11e9-8ac7-914186f48308.png">

**Comment by IceTeddy** [comment]
Forgive my poor English.Forgive me for using Google Translator.
I calculated the height.

<Header onLayout={this.getHeaderHeight}>
getHeaderHeight(event)
{
      let {height} = event.nativeEvent.layout;
      this.headerHeight = height;
}

<View style={{ flex: 1 }} onLayout={this.getContentHeight}>
getContentHeight(event)
{
      let {height} = event.nativeEvent.layout;
      this.contentHeight = height;
}

So~
let {width, height} = Dimensions.get('window');
let bottomBarHeight = height - this.headerHeight - this.contentHeight;

**Comment by sturmenta** [comment]
In `"react-navigation": "3.11.0",` I set this with
```
const createBottomTabNavigator(
  ...,
  {
    tabBarOptions: {
      style: {
        padding: 10,
        height: 80,
      },
    },
  },
);

```

https://reactnavigation.org/docs/en/bottom-tab-navigator.html

**Comment by osdnk** [comment]
This issue appears to be no longer valid

**Comment by leonardo2204** [comment]
@osdnk is there a final solution to do what is proposed in this issue? 
Thanks

**Comment by pie6k** [comment]
I came with solution without context etc.

```tsx
import React from 'react';
import { View } from 'react-native';
import { BottomTabBar } from 'react-navigation-tabs';
import { BottomTabBarProps } from 'react-navigation-tabs/lib/typescript/src/types';

// layout is stored as module variable
let tabBarLayout = {
  x: 0,
  y: 0,
  width: 0,
  height: 0,
};

// there is exported way to get current tabbar height
export function getTabBarHeight() {
  return tabBarLayout.height;
}

// there is simple tab bar component used when creating navigator that will update this layout
export function TabBarComponent(props: BottomTabBarProps) {
  return (
    <View
      collapsable={false}
      onLayout={(event) => {
        tabBarLayout = event.nativeEvent.layout;
      }}
    >
      <BottomTabBar {...props} />
    </View>
  );
}
```

Later on, I simply use this component, when creating navigator

```tsx
const HomeScreenTabs = createBottomTabNavigator(
  {
    ...calendarRoutes,
    ...taskScreenRoutes,
  },
  {
    tabBarComponent: TabBarComponent,
);
```

and then, I can just get tabbat height anywhere using exported `getTabBarHeight()`
